AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Severless-2016-10-31
Description: Rank & Match's Chatbot API

Globals:
  Function:
    Runtime: python3.11
    Timeout: 10
    MemorySize: 256

ChatApi:
  Type: AWS::Serverless::Api
  Properties:
    StageName: prod
    Cors:
      AllowMethods: "'OPTIONS,POST'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

ChatFunction:
  Type: AWS::Serverless::Function
  Properties:
    CodeUri: src/
    Handler: app.lambda_handler
    Events:
      ChatPost:
        Type: Api
        Properties:
          Path: /chat
          Method: post
          RestApiId: !Ref ChatApi

